FROM debian:buster-slim



RUN apt-get update && apt-get install -y curl xz-utils && rm -rf /var/lib/apt/lists/* \
    && export VERSION=$(curl -s "https://api.github.com/repos/klzgrad/naiveproxy/releases/latest" | jq -r .tag_name)
    && echo ">>>>>>>>>>>>>>> ${VERSION} ###############" 
    && curl --fail --silent -L https://github.com/klzgrad/naiveproxy/releases/download/${VERSION}/naiveproxy-${VERSION}-linux-x64.tar.xz | \
      tar xJvf - -C / \
    && mv /naiveproxy-${VERSION}-linux-x64/naive /usr/local/bin/naive
 
ENTRYPOINT [ "naive" ]
CMD [ "config.json" ]
